### ISSUE TITLE
crash ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by kaojistream** [BelooS/ChipsLayoutManager#23]
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.beloo.widget.chipslayoutmanager.cache.ParcelableContainer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2263)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.beloo.widget.chipslayoutmanager.cache.ParcelableContainer
	at android.os.Parcel.readParcelableCreator(Parcel.java:2147)
	at android.os.Parcel.readParcelable(Parcel.java:2097)
	at android.os.Parcel.readValue(Parcel.java:2013)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2363)
	at android.os.Parcel.readSparseArray(Parcel.java:1735)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer.<init>(ParcelableContainer.java:45)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer.<init>(ParcelableContainer.java:13)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer$1.createFromParcel(ParcelableContainer.java:79)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer$1.createFromParcel(ParcelableContainer.java:75)
	at android.os.Parcel.readParcelable(Parcel.java:2104)
	at android.support.v7.widget.RecyclerView$SavedState.<init>(RecyclerView.java:10003)
	at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:10027)
	at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:10024)
	at android.os.Parcel.readParcelable(Parcel.java:2104)
	at android.os.Parcel.readValue(Parcel.java:2013)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2363)
	at android.os.Parcel.readSparseArray(Parcel.java:1735)
	at android.os.Parcel.readValue(Parcel.java:2070)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
	at android.os.Bundle.unparcel(Bundle.java:249)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1736)
	at android.app.Activity.onRestoreInstanceState(Activity.java:944)
	at android.app.Activity.performRestoreInstanceState(Activity.java:916)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2241)
	... 11 more
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.beloo.widget.chipslayoutmanager.cache.ParcelableContainer
	at android.os.Parcel.readParcelableCreator(Parcel.java:2147)
	at android.os.Parcel.readParcelable(Parcel.java:2097)
	at android.os.Parcel.readValue(Parcel.java:2013)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2363)
	at android.os.Parcel.readSparseArray(Parcel.java:1735)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer.<init>(ParcelableContainer.java:45)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer.<init>(ParcelableContainer.java:13)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer$1.createFromParcel(ParcelableContainer.java:79)
	at com.beloo.widget.chipslayoutmanager.ParcelableContainer$1.createFromParcel(ParcelableContainer.java:75)
	at android.os.Parcel.readParcelable(Parcel.java:2104)
	at android.support.v7.widget.RecyclerView$SavedState.<init>(RecyclerView.java:10003)
	at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:10027)
	at android.support.v7.widget.RecyclerView$SavedState$1.createFromParcel(RecyclerView.java:10024)
	at android.os.Parcel.readParcelable(Parcel.java:2104)
	at android.os.Parcel.readValue(Parcel.java:2013)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2363)
	at android.os.Parcel.readSparseArray(Parcel.java:1735)
	at android.os.Parcel.readValue(Parcel.java:2070)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
	at android.os.Bundle.unparcel(Bundle.java:249)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1736)
	at android.app.Activity.onRestoreInstanceState(Activity.java:944)
	at android.app.Activity.performRestoreInstanceState(Activity.java:916)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2241)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by martintoften** [comment]
I got this too. Is there a solution to this?

**Comment by BelooS** [comment]
Could you try with newest version v0.3.5? If issue still occurs please provide additional information about it. Does it appear on orientation change? With/out don't keep activities setting? On which api?

**Comment by martintoften** [comment]
Nexux 6p 7.1. It occurs on application startup.
I'll try to update and see if that helps
