### ISSUE TITLE
NPE on objects move

### ISSUE THREAD

**Issue by dmytroKarataiev** [BelooS/ChipsLayoutManager#4]
That's not related to the library per se, but it'd also be nice to fix for the sample app.
When you delete chips from the recyclerview spinners aren't getting updated and you can get a NPE on Move.

`Caused by: java.lang.IndexOutOfBoundsException: Index: 38, Size: 31
at java.util.ArrayList.add(ArrayList.java:457)
at beloo.recyclerviewcustomadapter.MainActivity.onMoveClicked(MainActivity.java:162)
   at java.lang.reflect.Method.invoke(Native Method) 
      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) `

**Comment by BelooS** [comment]
Yep. My problem is that i maintain sample in the least. So such issues could appear time to time. 

Have fixed in dev branch
